@SERVER_URL = http://localhost:8000
@ACCESS_TOKEN=  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNzMWcxMjIyMzRAZ21haWwuY29tIiwidXNlcklkIjoiZDJjZWY0ZWItZjY3Yi00ZDYyLTg1NTEtMjU3MjE0OGJmODlmIiwiaWF0IjoxNzMxNjY2NjIwLCJleHAiOjE3MzE3NTMwMjB9.RRwXEvkYCAtIrvDqXgOY9sCUs6WZ714UHb71bYFyf6g
###


###
GET {{SERVER_URL}}/api/auth/google


###
POST {{SERVER_URL}}/api/auth/login
Content-Type: application/json

{
   "email":"admin@gmail.com",
   "password":"admin"
}

###
POST {{SERVER_URL}}/api/auth/register
Content-Type: application/json

{
   "email":"ss1g122234@gmail.com",
   "password":"s1ws"
}

###
GET {{SERVER_URL}}/api/users?email=19521750@gm.uit.edu.vn
Cookie: accessToken={{ACCESS_TOKEN}}

###
GET {{SERVER_URL}}/api/auth/me
Authorization: Bearer {{ACCESS_TOKEN}}


 