@SERVER_URL = http://localhost:8000
@ACCESS_TOKEN=  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNzMTIzNEBnbWFpbC5jb20iLCJ1c2VySWQiOiI4NTczMDYwZC02NGYxLTQ4ZTEtODdjMy1kNWVlNjZkMDIyNWEiLCJpYXQiOjE3MzE1NzU5OTksImV4cCI6MTczMTY2MjM5OX0.kn2KrvfbzzHPCpVjr25nyUxdnWpjH3dPqEAwj-GYfX8
###


###
GET {{SERVER_URL}}/api/auth/google


###
POST {{SERVER_URL}}/api/auth/login
Content-Type: application/json

{
   "email":"admin@gmail.com",
   "password":"admin"
}

###
POST {{SERVER_URL}}/api/auth/register
Content-Type: application/json

{
   "email":"ss1g122234@gmail.com",
   "password":"s1ws"
}

###
GET {{SERVER_URL}}/api/users?email=19521750@gm.uit.edu.vn
Authorization: Bearer {{ACCESS_TOKEN}}


###
GET {{SERVER_URL}}/api/auth/me
Authorization: Bearer {{ACCESS_TOKEN}}


 