@SERVER_URL = https://mina-backend.onrender.com
@ACCESS_TOKEN=  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNzMWcxMjIyMzRAZ21haWwuY29tIiwidXNlcklkIjoiNWFlYzcxN2EtYzE1MC00Yzc2LWJhYmUtZTk0MjY3NzA3M2UxIiwiaWF0IjoxNzM1MjI0MjU0LCJleHAiOjE3MzUzMTA2NTR9.4awu2MoiKPLFHh7mUeKZEeHUSf0AuoeOxw9z2WWGaR8
###


###
GET {{SERVER_URL}}/api/auth/google


###
POST {{SERVER_URL}}/api/auth/login
Content-Type: application/json

{
   "email":"ss1g122234@gmail.com",
   "password":"s1ws"
}

###
POST {{SERVER_URL}}/api/auth/register
Content-Type: application/json

{
   "email":"ss1g122234@gmail.com",
   "password":"s1ws"
}

###
GET {{SERVER_URL}}/api/users?email=ss1g122234@gmail.com
Cookie: accessToken={{ACCESS_TOKEN}}

###
GET {{SERVER_URL}}/api/auth/me
Authorization: Bearer {{ACCESS_TOKEN}}


 